### ISSUE TITLE
upon running the script i receive error

### ISSUE THREAD

**Issue by riyazshariff** [brianpardy/em13c#5]
/usr/bin/grep: /oraInst.loc: No such file or directory
/usr/bin/grep: /ContentsXML/inventory.xml: No such file or directory
AGENT_HOME not found in oraInventory, exiting...

**Comment by riyazshariff** [comment]
my environment - Oracle Linux 7 with EM13cR2 Installed.

**Comment by brianpardy** [comment]
Hello,

It appears the script is unable to identify your OMS_HOME directory.  The script uses the file /etc/oragchomelist (or if that is not found, /var/opt/oracle/oragchomelist) to identify your OMS_HOME.  Can you confirm for me if you have either of those files on your system?  If you do not, do you have an "oragchomelist" file anywhere on your system? I believe the EM13c install should create this file somewhere.

The contents of the /etc/oragchomelist file on my SLES11 SP4 system with EM13cR2 are three lines:
/oracle/oem/Middleware13cR2

/oracle/oem/agent13cR1/agent_13.2.0.0.0:/oracle/oem/agent13cR1/agent_inst

**Comment by riyazshariff** [comment]
Thanks for the quick response. For some reason default installation of EM 13cR2 entered only agent_home in /etc/oragchomelist file
My contents Before:
/u01/app/oracle/agent/agent_13.2.0.0.0:/u01/app/oracle/agent/agent_inst

I added OMS_HOME here and the script ran fine.
Thanks again.

**Comment by brianpardy** [comment]
Excellent, thank you for letting me know!
