### ISSUE TITLE
Script truncates long agent names

### ISSUE THREAD

**Issue by lamahmud** [brianpardy/em13c#7]
Your script for securing agents with strong ciphers truncates agents with long names.  For instance one of my agent names is something like:  adatabaseserver1.erm.secure.df.company.com:3872.  It gets truncated to adatabaseserver1.erm.secure.df.comp because the line wraps without the -script parameter in your line:
for agent in `$EMCLI get_targets -targets=oracle_emd | grep oracle_emd | awk '{print $4}'`
This line should read:

for agent in `$EMCLI get_targets -script -targets=oracle_emd | grep oracle_emd | awk '{print $4}'`

Also, if the agent is unreachable, awk '{print $4}' with render the line:  "oracle_emd" because awk '{print $4}' doesn't check for words that have spaces and just assumes you want the word after the fourth space.  If I find a better way to figure out how to handle "Agent Unreachable" I'll update the issue.

**Comment by lamahmud** [comment]
Try:

$EMCLI get_targets -format=name:csv targets=oracle_emd | grep oracle_emd | awk -F, '{print $4}'

This will use a comma separated line and awk will properly print the fourth column since emcli recognizes that "Agent Unreachable" is in one column not two.

**Comment by brianpardy** [comment]
Thank you very much for catching this bug.  I do not have any long agent names and so have not run into this.  I am working these changes in and will have an update on the beta branch you can try to test it out soon.

**Comment by brianpardy** [comment]
Hello, I pushed commit dd1878773aac7fea65ab6cbcbc27feff289c8079 to the beta branch using the updated $EMCLI line you suggested. It looks good on my system, but with no long agent names I cannot be sure.  Would you mind testing this fix?

Also, may I credit you by name or github username in the comments for providing the fix?

**Comment by brianpardy** [comment]
Apologies, I had typed awk -F: instead of awk -F, .  New commit 71f140136f6ffd0adf93a94eef7605b2c5dc18ba should work correctly now.

**Comment by lamahmud** [comment]
It works great!  Thanks!

**Comment by lamahmud** [comment]
You may want to add this to the agent wallet script as well.  I just caught the same bug there.
